### ISSUE TITLE
Expose a function to read the current lag value?

### ISSUE THREAD

**Issue by IwalkAlone** [nphollon/update-clock#1]
That way we could use it to extrapolate past the current physics state and compensate for the accumulated lag

**Comment by nphollon** [comment]
Could you show some example code that illustrates what you want to do? Like, assuming there was a `Clock.getLag` or something, how would you use it?

**Comment by IwalkAlone** [comment]
Here's an example based on the code you have in the README, implementing the lag compensation mechanism from the [game loop article](http://gameprogrammingpatterns.com/game-loop.html):
https://gist.github.com/IwalkAlone/cd5694f0ba339b5c7bfb2ea847dc2eaf

**Comment by nphollon** [comment]
OK, thanks for that! 

I think maybe it makes sense to pass the whole clock object to physicsUpdate, and have the predicted position be computed in there. I was on the fence about this before, because I wasn't sure the lag value would be useful.

**Comment by IwalkAlone** [comment]
I don't think that would work out, as the idea here is that the predicted position should be recalculated every animationFrame, but `physicsUpdate` is called on a fixed timestep. Also, in a real application `physicsUpdate` will probably be much more expensive than `predict`. So keeping them separate from each other seems like the way to go.

**Comment by nphollon** [comment]
Of course, you're right. Thanks for the input!
